[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "https://blog.matt-thorning.dev/*"
  to = "https://stupefied-beaver.netlify.app/blog/:splat"
  status = 200
  force = true
